import json
import time
import os
from pathlib import Path
from graph import security_pipeline
from tools import generate_system_context, get_code_snippet, get_infrastructure_context

# JSON 리포트 경로
SEMGREP_JSON = Path("reports/semgrep/semgrep_for_llm.json")
TRIVY_JSON = Path("reports/trivy/trivy_for_llm.json")
ZAP_JSON = Path("reports/zap/zap_for_llm.json")
FINAL_MD = Path("reports/summary/ai_final_report.md")

def run_agent_for_finding(scan_tool: str, vuln_data: dict, sys_context: str) -> str:
    """단일 취약점 데이터를 LangGraph에 통과시키고 마크다운 결과를 받습니다."""
    initial_state = {
        "scan_tool": scan_tool,
        "system_context": sys_context,
        "vuln_data": vuln_data
    }
    
    # LangGraph 실행
    final_state = security_pipeline.invoke(initial_state)
    return final_state["final_report_md"]

def get_infrastructure_context(root_dir: str) -> str:
    """Trivy 분석에 필요한 핵심 설정 파일들의 내용을 묶어서 반환합니다."""
    context = ""
    target_files = {
        "pom.xml": "backend/pom.xml",
        "application.yml": "backend/src/main/resources/application.yml",
        "Dockerfile": "backend/Dockerfile"
    }
    
    for name, relative_path in target_files.items():
        full_path = os.path.join(root_dir, relative_path)
        if os.path.exists(full_path):
            with open(full_path, "r", encoding="utf-8") as f:
                content = f.read()
                # 앞부분 3000자만 추출 
                context += f"\n### [{name}]\n```\n{content[:3000]}\n```\n"
    return context

def main():
    print("[*] Starting AI DevSecOps Pipeline...")
    sys_context = generate_system_context("../../") # 프로젝트 루트 경로
    infra_context = get_infrastructure_context("../../")
    
    FINAL_MD.parent.mkdir(parents=True, exist_ok=True)
    
    with open(FINAL_MD, "w", encoding="utf-8") as f:
        f.write("# 🤖 AI DevSecOps Integrated Security Report\n\n")
        f.write("> **Note:** This report is generated by AI Agent traversing SAST, DAST, and Dependency scans.\n\n")
        
        # ==========================================
        # 1. SAST (Semgrep) 처리
        # ==========================================
        if SEMGREP_JSON.exists():
            with open(SEMGREP_JSON, "r") as jf:
                sast_findings = json.load(jf)
            
            if sast_findings:
                print(f"[*] Processing {len(sast_findings)} SAST findings...")
                f.write("## 1. SAST Findings (Source Code)\n\n")
                
                for vuln in sast_findings:
                    # 라인 번호 파싱 및 +-30줄 추출
                    line_raw = str(vuln.get("line_number", "0")).split('-')[0]
                    line_num = int(line_raw) if line_raw.isdigit() else 0
                    
                    if line_num > 0 and vuln.get("file_path"):
                        code_chunk = get_code_snippet(vuln["file_path"], line_num)
                        vuln["raw_code_chunk"] = code_chunk
                    
                    report_md = run_agent_for_finding("SAST", vuln, sys_context)
                    f.write(report_md + "\n\n")
                    time.sleep(0.5)
                    
        # ==========================================
        # 2. Dependency (Trivy) 처리
        # ==========================================
        if TRIVY_JSON.exists():
            with open(TRIVY_JSON, "r") as jf:
                trivy_findings = json.load(jf)
            
            if trivy_findings:
                print(f"[*] Processing {len(trivy_findings)} Trivy findings...")
                f.write("---\n## 2. Dependency & Container Findings\n\n")
                
                for vuln in trivy_findings:
                    vuln["infrastructure_files"] = infra_context 
                    report_md = run_agent_for_finding("Trivy", vuln, sys_context)
                    f.write(report_md + "\n\n")
                    time.sleep(0.5)
                    
        # ==========================================
        # 3. DAST (ZAP) 처리
        # ========================================== 
        if ZAP_JSON.exists():
            with open(ZAP_JSON, "r") as jf:
                zap_findings = json.load(jf)
            
            if zap_findings:
                print(f"[*] Processing {len(zap_findings)} ZAP findings...")
                f.write("---\n## 3. DAST Findings (Dynamic Analysis)\n\n")
                
                for vuln in zap_findings:
                    report_md = run_agent_for_finding("DAST", vuln, sys_context)
                    f.write(report_md + "\n\n")
                    time.sleep(0.5)

    print(f"[+] AI Analysis Complete! Final report saved to: {FINAL_MD}")

if __name__ == "__main__":
    main()