import sys
import os
import json
import time
from pathlib import Path

# 현재 파일(run_ai_pipeline.py)의 부모의 부모 폴더인 'scripts' 경로를 sys.path에 강제 주입
scripts_dir = str(Path(__file__).resolve().parent.parent)
if scripts_dir not in sys.path:
    sys.path.insert(0, scripts_dir)

from workflow import security_pipeline
from tools import generate_system_context, get_project_tree, get_infrastructure_context, get_merged_snippets

# JSON 리포트 경로
SEMGREP_JSON = Path("reports/semgrep/semgrep_for_llm.json")
CODEQL_JSON = Path("reports/codeql/codeql_for_llm.json")
TRIVY_JSON = Path("reports/trivy/trivy_for_llm.json")
ZAP_JSON = Path("reports/zap/zap_for_llm.json")
SCHEMATHESIS_JSON = Path("reports/openapi/schemathesis_for_llm.json")
FINAL_MD = Path("reports/summary/ai_final_report.md")

ai_records = []

def _record(scan_tool: str, vuln: dict, final_state: dict):
    """7-Phase 아키텍처에 맞추어 모든 중간 분석 결과를 JSON으로 기록합니다."""
    # state.py 에 정의된 키값에 정확히 매핑
    triage = final_state.get("triage")
    root_cause = final_state.get("root_cause")
    validation = final_state.get("validation")
    risk = final_state.get("risk_assessment")

    # 대상 파일 경로 추출의 파편화 방지
    target_path = vuln.get("file_path") or vuln.get("package_name") or vuln.get("test_case") or "Unknown"
    if scan_tool == "DAST" and vuln.get("affected_targets"):
        target_path = vuln["affected_targets"][0].get("url", "Unknown")

    ai_records.append({
        "scan_tool": scan_tool,
        "rule_id": vuln.get("rule_id") or vuln.get("cve_id") or vuln.get("alert_name") or "Unknown",
        "cwe": vuln.get("cwe") or vuln.get("cwe_id") or "Unknown",
        "file_path": target_path,
        "line_number": vuln.get("line_number") or "N/A",
        
        # Pydantic 객체일 경우 model_dump() 호출. 오탐(FP) 등으로 None일 경우 빈 딕셔너리 처리
        "triage": triage.model_dump() if triage else {},
        "root_cause": root_cause.model_dump() if root_cause else {},
        "assessment": risk.model_dump() if risk else {},
    })

def run_agent_for_finding(scan_tool: str, vuln_data: dict, sys_context: str, proj_tree: str) -> dict:
    """단일 취약점 데이터를 LangGraph에 통과시키고 전체 상태를 받습니다."""
    initial_state = {
        "scan_tool": scan_tool,
        "system_context": sys_context,
        "project_tree": proj_tree,
        "vuln_data": vuln_data,
        "loop_count": 0  
    }
    final_state = security_pipeline.invoke(initial_state)
    return final_state

def main():
    print("[*] Starting AI DevSecOps Pipeline (7-Phase Agentic Architecture)...")
    project_root = str(Path(__file__).resolve().parent.parent.parent) # 프로젝트 루트 경로
    
    sys_context = generate_system_context()
    proj_tree = get_project_tree(project_root)
    infra_context = get_infrastructure_context(project_root)
    
    FINAL_MD.parent.mkdir(parents=True, exist_ok=True)
    
    with open(FINAL_MD, "w", encoding="utf-8") as f:
        f.write("# 🤖 AI DevSecOps Integrated Security Report\n\n")
        f.write("> **Note:** This report is generated by an autonomous Multi-Agent architecture exploring CodeQL, SAST, DAST, and SCA findings.\n\n")

        # ==========================================
        # 1. SAST (Semgrep) 처리
        # ==========================================
        if SEMGREP_JSON.exists():
            with open(SEMGREP_JSON, "r", encoding="utf-8") as jf:
                sast_findings = json.load(jf)
            
            if sast_findings:
                print(f"[*] Processing {len(sast_findings)} SAST findings...")
                f.write("## 1. SAST Findings (Source Code)\n\n")
                
                for vuln in sast_findings:
                    # 파이썬 청킹 제거: Phase 1 에이전트가 스스로 도구를 사용해 읽음!
                    final_state = run_agent_for_finding("SAST", vuln, sys_context, proj_tree) 
                    report_md = final_state.get("final_report_md", "[Error] Report generation failed.")
                    
                    _record("SAST", vuln, final_state)
                    f.write(report_md + "\n\n")
                    time.sleep(0.5)

        # ==========================================
        # 2. Advanced SAST (CodeQL) 처리
        # ==========================================
        if CODEQL_JSON.exists():
            with open(CODEQL_JSON, "r", encoding="utf-8") as jf:
                codeql_findings = json.load(jf)
            
            if codeql_findings:
                print(f"[*] Processing {len(codeql_findings)} CodeQL findings...")
                f.write("---\n## 2. Advanced SAST Findings (CodeQL Data Flow)\n\n")
                
                for vuln in codeql_findings:
                    data_flow = vuln.get("data_flow", [])
                    prefetched_code = get_merged_snippets(data_flow, project_root, margin=30)
                    vuln["prefetched_code"] = prefetched_code

                    final_state = run_agent_for_finding("CodeQL", vuln, sys_context, proj_tree)
                    report_md = final_state.get("final_report_md", "[Error] Report generation failed.")
                    
                    _record("CodeQL", vuln, final_state)
                    f.write(report_md + "\n\n")
                    time.sleep(0.5)
 
        # ==========================================
        # 3. Dependency (Trivy) 처리
        # ==========================================
        if TRIVY_JSON.exists():
            with open(TRIVY_JSON, "r", encoding="utf-8") as jf:
                trivy_findings = json.load(jf)
            
            if trivy_findings:
                print(f"[*] Processing {len(trivy_findings)} Trivy findings...")
                f.write("---\n## 3. Dependency & Container Findings\n\n")
                
                for vuln in trivy_findings:
                    vuln["infrastructure_files"] = infra_context 
                    final_state = run_agent_for_finding("Trivy", vuln, sys_context, proj_tree)
                    report_md = final_state.get("final_report_md", "[Error] Report generation failed.")
                    
                    _record("Trivy", vuln, final_state)
                    f.write(report_md + "\n\n")
                    time.sleep(0.5)
                    
        # ==========================================
        # 4. DAST (ZAP) 처리
        # ========================================== 
        if ZAP_JSON.exists():
            with open(ZAP_JSON, "r", encoding="utf-8") as jf:
                zap_findings = json.load(jf)
            
            if zap_findings:
                print(f"[*] Processing {len(zap_findings)} ZAP findings...")
                f.write("---\n## 4. DAST Findings (Dynamic Analysis)\n\n")
                
                for vuln in zap_findings:
                    final_state = run_agent_for_finding("DAST", vuln, sys_context, proj_tree)
                    report_md = final_state.get("final_report_md", "[Error] Report generation failed.")
                    
                    _record("DAST", vuln, final_state)
                    f.write(report_md + "\n\n")
                    time.sleep(0.5)

        # ==========================================
        # 5. API Fuzzing (Schemathesis) 처리
        # ========================================== 
        if SCHEMATHESIS_JSON.exists():
            with open(SCHEMATHESIS_JSON, "r", encoding="utf-8") as jf:
                schema_findings = json.load(jf)
            
            if schema_findings:
                print(f"[*] Processing {len(schema_findings)} Schemathesis findings...")
                f.write("---\n## 5. API Fuzzing Findings (Schemathesis)\n\n")
                
                for vuln in schema_findings:
                    final_state = run_agent_for_finding("Schemathesis", vuln, sys_context, proj_tree)
                    report_md = final_state.get("final_report_md", "[Error] Report generation failed.")
                    
                    _record("Schemathesis", vuln, final_state)
                    f.write(report_md + "\n\n")
                    time.sleep(0.5)

    # 최종 분석 결과를 JSON 형태로 저장 (대시보드 등 연동용)
    (FINAL_MD.parent / "ai_findings.json").write_text(
        json.dumps(ai_records, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"[+] AI Analysis Complete! Final report saved to: {FINAL_MD}")

if __name__ == "__main__":
    main()